### ISSUE TITLE
Update geplant?

### ISSUE THREAD

**Issue by madoe01** [lars85/TYPO3-Extensions-lp_fussballde#3]
Leider wird die Extrension, die in alten TYPO3-Installationen prima lief seit 2014 nicht mehr weiter entwickelt und in den aktuellen Versionen läuft sie nicht wirklich. Ist ein Update geplant (ich nutze derzeit 9.5.20) oder wurde das Projekt eingestellt. Die Extension war eine feine Sache - wäre also schön, wenn es nicht mit allzu viel Aufwand verbunden ist, wenn diese auf die aktuellen Versionen upgedatet werden würde.

**Comment by lars85** [comment]
da ich sie selbst aktiv nicht mehr verwende, ist leider aktuell kein Update geplant.

es kann jedoch super gerne jemand anderes das Update durchführen und hier einen Merge-Request stellen.

Viele Grüsse
